version: '3.8'

services:
  imaging_data:
    build: 
      context: ./services/imaging_data
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ${LOCAL_DICOM_PATH}:/data/dicom:ro  # Read-only mount
    environment:
      - UPLOAD_DIR=/data/dicom
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  tumor_analysis:
    build: 
      context: ./services/tumor_analysis
      dockerfile: Dockerfile
    volumes:
      - ${LOCAL_DICOM_PATH}:/data/dicom:ro
      - processed_data:/data/processed
      - segmentation_data:/data/segmentations
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # För GPU-stöd
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: neuro-platform-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_VERSION=22.14.0
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:
  processed_data:
  segmentation_data: 