export enum ViewportType {
  STACK = 'STACK',
  VOLUME = 'VOLUME',
  ORTHOGRAPHIC = 'ORTHOGRAPHIC',
  PERSPECTIVE = 'PERSPECTIVE'
}

export enum Events {
  ELEMENT_ENABLED = 'ELEMENT_ENABLED',
  ELEMENT_DISABLED = 'ELEMENT_DISABLED',
  IMAGE_RENDERED = 'IMAGE_RENDERED',
  IMAGE_LOADED = 'IMAGE_LOADED',
  VOLUME_LOADED = 'VOLUME_LOADED'
}

export enum OrientationAxis {
  AXIAL = 'AXIAL',
  SAGITTAL = 'SAGITTAL',
  CORONAL = 'CORONAL'
} 